const mainFunctions = require("./main");

module.exports = {
  // main Database
  // Fee Db Object
  dbGetFee: mainFunctions.dbGetFee,
  dbCreateFee: mainFunctions.dbCreateFee,
  dbUpdateFee: mainFunctions.dbUpdateFee,
  dbDeleteFee: mainFunctions.dbDeleteFee,
  dbListFees: mainFunctions.dbListFees,
  dbCheckoutstartFee: mainFunctions.dbCheckoutstartFee,
  dbCheckoutcompleteFee: mainFunctions.dbCheckoutcompleteFee,
  dbCheckoutrefreshFee: mainFunctions.dbCheckoutrefreshFee,
  createFee: mainFunctions.createFee,
  getIdListOfFeeByField: mainFunctions.getIdListOfFeeByField,
  getFeeById: mainFunctions.getFeeById,
  getFeeAggById: mainFunctions.getFeeAggById,
  getFeeListByQuery: mainFunctions.getFeeListByQuery,
  getFeeStatsByQuery: mainFunctions.getFeeStatsByQuery,
  getFeeByQuery: mainFunctions.getFeeByQuery,
  updateFeeById: mainFunctions.updateFeeById,
  updateFeeByIdList: mainFunctions.updateFeeByIdList,
  updateFeeByQuery: mainFunctions.updateFeeByQuery,
  deleteFeeById: mainFunctions.deleteFeeById,
  deleteFeeByQuery: mainFunctions.deleteFeeByQuery,
  updateFeeOrderStatusById: mainFunctions.updateFeeOrderStatusById,

  // FeePayment Db Object
  dbGetFeepayment: mainFunctions.dbGetFeepayment,
  dbCreateFeepayment: mainFunctions.dbCreateFeepayment,
  dbUpdateFeepayment: mainFunctions.dbUpdateFeepayment,
  dbDeleteFeepayment: mainFunctions.dbDeleteFeepayment,
  dbListFeepayments: mainFunctions.dbListFeepayments,
  createFeePayment: mainFunctions.createFeePayment,
  getIdListOfFeePaymentByField: mainFunctions.getIdListOfFeePaymentByField,
  getFeePaymentById: mainFunctions.getFeePaymentById,
  getFeePaymentAggById: mainFunctions.getFeePaymentAggById,
  getFeePaymentListByQuery: mainFunctions.getFeePaymentListByQuery,
  getFeePaymentStatsByQuery: mainFunctions.getFeePaymentStatsByQuery,
  getFeePaymentByQuery: mainFunctions.getFeePaymentByQuery,
  updateFeePaymentById: mainFunctions.updateFeePaymentById,
  updateFeePaymentByIdList: mainFunctions.updateFeePaymentByIdList,
  updateFeePaymentByQuery: mainFunctions.updateFeePaymentByQuery,
  deleteFeePaymentById: mainFunctions.deleteFeePaymentById,
  deleteFeePaymentByQuery: mainFunctions.deleteFeePaymentByQuery,

  // FeeEvent Db Object
  dbGetFeeevent: mainFunctions.dbGetFeeevent,
  dbCreateFeeevent: mainFunctions.dbCreateFeeevent,
  dbUpdateFeeevent: mainFunctions.dbUpdateFeeevent,
  dbDeleteFeeevent: mainFunctions.dbDeleteFeeevent,
  dbListFeeevents: mainFunctions.dbListFeeevents,
  createFeeEvent: mainFunctions.createFeeEvent,
  getIdListOfFeeEventByField: mainFunctions.getIdListOfFeeEventByField,
  getFeeEventById: mainFunctions.getFeeEventById,
  getFeeEventAggById: mainFunctions.getFeeEventAggById,
  getFeeEventListByQuery: mainFunctions.getFeeEventListByQuery,
  getFeeEventStatsByQuery: mainFunctions.getFeeEventStatsByQuery,
  getFeeEventByQuery: mainFunctions.getFeeEventByQuery,
  updateFeeEventById: mainFunctions.updateFeeEventById,
  updateFeeEventByIdList: mainFunctions.updateFeeEventByIdList,
  updateFeeEventByQuery: mainFunctions.updateFeeEventByQuery,
  deleteFeeEventById: mainFunctions.deleteFeeEventById,
  deleteFeeEventByQuery: mainFunctions.deleteFeeEventByQuery,

  // FeePayment Db Object
  dbGetPayment: mainFunctions.dbGetPayment,
  dbGetPaymentbyorderid: mainFunctions.dbGetPaymentbyorderid,
  dbGetPaymentbypaymentid: mainFunctions.dbGetPaymentbypaymentid,
  dbCreatePayment: mainFunctions.dbCreatePayment,
  dbUpdatePayment: mainFunctions.dbUpdatePayment,
  dbListPayments: mainFunctions.dbListPayments,
  dbDeletePayment: mainFunctions.dbDeletePayment,
  createFeePayment: mainFunctions.createFeePayment,
  getIdListOfFeePaymentByField: mainFunctions.getIdListOfFeePaymentByField,
  getFeePaymentById: mainFunctions.getFeePaymentById,
  getFeePaymentAggById: mainFunctions.getFeePaymentAggById,
  getFeePaymentListByQuery: mainFunctions.getFeePaymentListByQuery,
  getFeePaymentStatsByQuery: mainFunctions.getFeePaymentStatsByQuery,
  getFeePaymentByQuery: mainFunctions.getFeePaymentByQuery,
  updateFeePaymentById: mainFunctions.updateFeePaymentById,
  updateFeePaymentByIdList: mainFunctions.updateFeePaymentByIdList,
  updateFeePaymentByQuery: mainFunctions.updateFeePaymentByQuery,
  deleteFeePaymentById: mainFunctions.deleteFeePaymentById,
  deleteFeePaymentByQuery: mainFunctions.deleteFeePaymentByQuery,
  getFeePaymentByOrderId: mainFunctions.getFeePaymentByOrderId,

  // PaymentCustomer Db Object
  dbGetCustomerbyuserid: mainFunctions.dbGetCustomerbyuserid,
  dbListCustomers: mainFunctions.dbListCustomers,
  createPaymentCustomer: mainFunctions.createPaymentCustomer,
  getIdListOfPaymentCustomerByField:
    mainFunctions.getIdListOfPaymentCustomerByField,
  getPaymentCustomerById: mainFunctions.getPaymentCustomerById,
  getPaymentCustomerAggById: mainFunctions.getPaymentCustomerAggById,
  getPaymentCustomerListByQuery: mainFunctions.getPaymentCustomerListByQuery,
  getPaymentCustomerStatsByQuery: mainFunctions.getPaymentCustomerStatsByQuery,
  getPaymentCustomerByQuery: mainFunctions.getPaymentCustomerByQuery,
  updatePaymentCustomerById: mainFunctions.updatePaymentCustomerById,
  updatePaymentCustomerByIdList: mainFunctions.updatePaymentCustomerByIdList,
  updatePaymentCustomerByQuery: mainFunctions.updatePaymentCustomerByQuery,
  deletePaymentCustomerById: mainFunctions.deletePaymentCustomerById,
  deletePaymentCustomerByQuery: mainFunctions.deletePaymentCustomerByQuery,
  getPaymentCustomerByUserId: mainFunctions.getPaymentCustomerByUserId,
  getPaymentCustomerByCustomerId: mainFunctions.getPaymentCustomerByCustomerId,

  // PaymentMethod Db Object
  dbDoListethods: mainFunctions.dbDoListethods,
  createPaymentMethod: mainFunctions.createPaymentMethod,
  getIdListOfPaymentMethodByField:
    mainFunctions.getIdListOfPaymentMethodByField,
  getPaymentMethodById: mainFunctions.getPaymentMethodById,
  getPaymentMethodAggById: mainFunctions.getPaymentMethodAggById,
  getPaymentMethodListByQuery: mainFunctions.getPaymentMethodListByQuery,
  getPaymentMethodStatsByQuery: mainFunctions.getPaymentMethodStatsByQuery,
  getPaymentMethodByQuery: mainFunctions.getPaymentMethodByQuery,
  updatePaymentMethodById: mainFunctions.updatePaymentMethodById,
  updatePaymentMethodByIdList: mainFunctions.updatePaymentMethodByIdList,
  updatePaymentMethodByQuery: mainFunctions.updatePaymentMethodByQuery,
  deletePaymentMethodById: mainFunctions.deletePaymentMethodById,
  deletePaymentMethodByQuery: mainFunctions.deletePaymentMethodByQuery,
  getPaymentMethodByPaymentMethodId:
    mainFunctions.getPaymentMethodByPaymentMethodId,
  getPaymentMethodByUserId: mainFunctions.getPaymentMethodByUserId,
  getPaymentMethodByCustomerId: mainFunctions.getPaymentMethodByCustomerId,
};
